/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppLanesRouteImport } from './routes/app.lanes'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppMIdRouteImport } from './routes/app.m.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppLanesRoute = AppLanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMIdRoute = AppMIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/lanes': typeof AppLanesRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/lanes': typeof AppLanesRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app': typeof AppIndexRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/activity': typeof AppActivityRoute
  '/app/create': typeof AppCreateRoute
  '/app/lanes': typeof AppLanesRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/m/$id': typeof AppMIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/create'
    | '/app/lanes'
    | '/app/portfolio'
    | '/app/'
    | '/app/m/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/activity'
    | '/app/create'
    | '/app/lanes'
    | '/app/portfolio'
    | '/app'
    | '/app/m/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/activity'
    | '/app/create'
    | '/app/lanes'
    | '/app/portfolio'
    | '/app/'
    | '/app/m/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lanes': {
      id: '/app/lanes'
      path: '/lanes'
      fullPath: '/app/lanes'
      preLoaderRoute: typeof AppLanesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/m/$id': {
      id: '/app/m/$id'
      path: '/m/$id'
      fullPath: '/app/m/$id'
      preLoaderRoute: typeof AppMIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCreateRoute: typeof AppCreateRoute
  AppLanesRoute: typeof AppLanesRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMIdRoute: typeof AppMIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCreateRoute: AppCreateRoute,
  AppLanesRoute: AppLanesRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppIndexRoute: AppIndexRoute,
  AppMIdRoute: AppMIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
